# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-04 01:37
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrera', models.CharField(blank=True, max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('avatar', models.ImageField(blank=True, upload_to=accounts.models.upload_location)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('carrera', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Carrera', verbose_name='Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.SmallIntegerField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='semestre',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Semestre', verbose_name='Semestre'),
        ),
    ]
