# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-04 01:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='carrera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Carrera', verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='semestre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Semestre', verbose_name='Semestre'),
        ),
    ]
