# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-04 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170903_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestre',
            name='semestre',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
